;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Effect.Buff.Stamina",NewTagName="Effect.Buff.StaminaRegen")
+GameplayTagList=(Tag="Cues.Instant.RedBurst",DevComment="")
+GameplayTagList=(Tag="Cues.Loop.Dash",DevComment="")
+GameplayTagList=(Tag="Cues.Loop.Poison",DevComment="")
+GameplayTagList=(Tag="Cues.Loop.Sprint",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.HealthRgen",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.ManaRegen",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.ShrineAll",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.ShrineHealthRegen",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.ShrineManaRegen",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.ShrineStaminaRegen",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="Event.Character.Death",DevComment="")
+GameplayTagList=(Tag="Event.Character.Exhausted",DevComment="")
+GameplayTagList=(Tag="State.Agile",DevComment="")
+GameplayTagList=(Tag="State.Airborne",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Crippled",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stunned",DevComment="")
+GameplayTagList=(Tag="State.Grounded",DevComment="")
+GameplayTagList=(Tag="State.Immortality",DevComment="")
+GameplayTagList=(Tag="State.Immunity.Poison",DevComment="")
+GameplayTagList=(Tag="State.Physical.Damage",DevComment="")
+GameplayTagList=(Tag="State.Physical.Heal",DevComment="")
+GameplayTagList=(Tag="State.Poision",DevComment="")
+GameplayTagList=(Tag="State.Resting",DevComment="")
+GameplayTagList=(Tag="State.Sprinting",DevComment="")
+GameplayTagList=(Tag="Stats.Base.Armor",DevComment="")
+GameplayTagList=(Tag="Stats.Base.Health",DevComment="")
+GameplayTagList=(Tag="Stats.Base.Mana",DevComment="")
+GameplayTagList=(Tag="Stats.Base.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Stats.Base.MaxMana",DevComment="")
+GameplayTagList=(Tag="Stats.Base.MaxShield",DevComment="")
+GameplayTagList=(Tag="Stats.Base.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Stats.Base.Shield",DevComment="")
+GameplayTagList=(Tag="Stats.Base.Stamina",DevComment="")
+GameplayTagList=(Tag="Stats.Regen.Health",DevComment="")
+GameplayTagList=(Tag="Stats.Regen.Mana",DevComment="")
+GameplayTagList=(Tag="Stats.Regen.Stamina",DevComment="")
+GameplayTagList=(Tag="Stats.Resistance.Armor",DevComment="")
+GameplayTagList=(Tag="Stats.Resistance.Poison",DevComment="")

